### ISSUE TITLE
Novel XML

### ISSUE THREAD

**Issue by NoOne2246** [jhuangmystery/btReader#1]
within xml, there are chapter nodes without any attributes set:
"<" chapter /">"
ignore the quotation marks
Don't know if something clears them or not, but this might need to be looked at.
However going to web api's, these chapter nodes should not be there as all other introduction and things are accounted for.

**Comment by jhuangmystery** [comment]
Not even an issue... The chapter nodes shouldn't have anything unless the user downloads it -> They should be empty. The chapter nodes will get something later on, once the user selects it.

**Comment by jhuangmystery** [comment]
Actually, I see what you mean, I thought you meant that there was no information downloaded for the chapter. Umm.. I'll look into it (but I'll probs just do a quick and dirty clear broken/empty nodes)

**Comment by NoOne2246** [comment]
The novel title also has several Title="" attributes rather than one.
