### ISSUE TITLE
Hidan no Aria list crash

### ISSUE THREAD

**Issue by NoOne2246** [jhuangmystery/btReader#13]
tell it to replace the external link with normal text and that it is not an image
check:
[http
first, if it is that, then it is not an image and just continue on with text.

**Comment by jhuangmystery** [comment]
I'll work on a quick fix for this, but it *SHOULD* actually be fixed in the new wikiparser thing.

**Comment by NoOne2246** [comment]
it will be fixed in my thing quick fix is to check for [[, as single [ will mean either external link or not a link at all.

**Comment by jhuangmystery** [comment]
Did the quick and dirty patch to fix this issue. Merging into master after testing is done. @NoOne2246 Should I close this, or do you want to take a look at the stuff first?

**Comment by NoOne2246** [comment]
close it if it works

**Comment by NoOne2246** [comment]
welp all images are connected with [[image:image.jpg or [[file:image.jpg
