### ISSUE TITLE
Wikitext parsing issue (another one)

### ISSUE THREAD

**Issue by jhuangmystery** [jhuangmystery/btReader#14]
tl;dr because our current "parsing" is just a hacky hard-code, there are a few more exceptions which break the code. Hopefully this thread will just store all the exceptions that are found.

Look at this page!

http://www.baka-tsuki.org/project/index.php?title=I%27m_a_High_School_Boy_and_a_Bestselling_Light_Novel_author,_strangled_by_my_female_classmate_who_is_my_junior_and_a_voice_actress

It doesn't exit out of the volumes section and so it picks up the category=Light_novel(English) and tries to DL it as an image.

**Comment by jhuangmystery** [comment]
Also, &quot; and other garbage keeps getting sent via the API. @NoOne2246 what was the API call that you said could clean the stuff up?

**Comment by NoOne2246** [comment]
I didn't use any special, just whatever was in the current code cleaned it up already, or did for other ones

**Comment by NoOne2246** [comment]
the garbage you are seeing is where they use html markup to make things italics rather than
<h level="3" i="6">===[[This_title_is_too_long!:Volume1|Volume 1 - Time to Play - First Half]]===</h>
these markups are redundant. So I need to remove these idiotic things that he has done.

**Comment by NoOne2246** [comment]
http://www.baka-tsuki.org/project/api.php?action=parse&prop=wikitext|revid|links&format=xml&page=I%27m_a_High_School_Boy_and_a_Bestselling_Light_Novel_author,_strangled_by_my_female_classmate_who_is_my_junior_and_a_voice_actress

try this
