### ISSUE TITLE
The novel title has several Title=""

### ISSUE THREAD

**Issue by jhuangmystery** [jhuangmystery/btReader#3]
Probs another quick fix, but I'll leave here just in case I don't get around to doing it

**Comment by jhuangmystery** [comment]
@NoOne2246 Could you please clarify this -> Do you mean the volume titles or the actual novel itself? (I've done a mini "fix" for the volume title, but if it's the actual novel, it might not be a quick patch to fix)

**Comment by NoOne2246** [comment]
volume Titles.
